### ISSUE TITLE
Feature Request: Multiple Build Types

### ISSUE THREAD

**Issue by kyleknighted** [jharding/grunt-sed#2]
Hey, it would be great if it supported multiple build phases. Development, Staging, Product, etc...

I tend to have specific replacements that happen for different phases of development/deployment and would really like to take it out of my node app and put it into Grunt.

If I end up with some free time, maybe I can help contribute a potential solution for something like this - but figured I'd toss it out there.

Thanks!!

**Comment by kyleknighted** [comment]
Ha. Nevermind. Should've read the README a little closer. Thanks for the great script - implementing now!

**Comment by jharding** [comment]
No problem, I wrote the README in a hurry so it's not very in-depth. I'll have to revisit it when I get a chance.
